name: CI/CD - Test, Build & Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Run tests and generate coverage report
        run: npx vitest run --coverage | tee coverage/coverage-summary.txt

      - name: Update Coverage in README
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          
          COVERAGE=$(jq -r '.total.statements.pct' coverage/coverage-summary.json)
          COVERAGE_INT=${COVERAGE%.*}
          
          if (( COVERAGE_INT < 50 )); then
              COLOR="red"
          elif (( COVERAGE_INT < 80 )); then
              COLOR="yellow"
          else
              COLOR="green"
          fi
          
          BADGE_URL="https://img.shields.io/badge/coverage-${COVERAGE}%25-${COLOR}"
          NEW_BADGE_CONTENT="![Coverage](${BADGE_URL})"
          
          COVERAGE_TABLE=$(cat coverage/coverage-summary.txt)
          NEW_TABLE_CONTENT="\`\`\`\n${COVERAGE_TABLE}\n\`\`\`"
          
          perl -0777 -i -pe "s|(<!-- COVERAGE_BADGE_START -->).*?(<!-- COVERAGE_BADGE_END -->)|\1 ${NEW_BADGE_CONTENT} \2|s" README.md
          perl -0777 -i -pe "s|(<!-- COVERAGE_TABLE_START -->).*?(<!-- COVERAGE_TABLE_END -->)|\1\n${NEW_TABLE_CONTENT}\n\2|s" README.md
          
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          if ! git diff --quiet README.md; then
            git add README.md
            git commit -m "docs(coverage): Update test coverage in README [skip ci]"
            git push
          else
            echo "No changes in coverage to commit."
          fi

      - name: Build project
        run: npm run build

      - name: Zip dist folder
        run: zip -r dist.zip ./dist

      - name: Deploy to shared hosting
        run: |
          curl -X POST \
            -F "file=@dist.zip" \
            -F "token=${{ secrets.DEPLOYER_TOKEN }}" \
            "${{ secrets.DEPLOYER_URL }}"